<footer class="footer">
    Contact Us:<br>
        <div class ="contactus">
        <a href="mailto:103523649@student.swin.edu.au" title="mail to"><img src="styles/images/mail.png" alt="email" id="culogo1"></a>
        <a href="tel:+6281703835030"><img src="styles/images/phone.png" alt="phone" id="culogo2"></a>
        <a href="https://www.instagram.com/jes.bg" title="instagram"><img src="styles/images/ig.png" alt="instagram" id="culogo3"></a>
        </div>
    
    </footer>