<header class="header">
    <div class="container">
    <h1><a href="index.html">Je-Tech</a></h1>
    <nav class="menu">
        <div id="navicon">
            <i class="fas fa-bars"></i>
        </div>
<ul>
    <li class="limenu"><a href="index.php">Home</a></li>
    <li class="limenu"><a href="jobs.php">Jobs</a></li>
    <li class="limenu"><a href="apply.php">Apply</a></li>
    <li class="limenu"><a href="about.php">About</a></li>
    <li class="limenu"><a href="manager.php">Manager</a></li>
</ul>
    </nav>
    </div>
 </header>
